### ISSUE TITLE
Make change of frequency easier

### ISSUE THREAD

**Issue by dan-nkl** [dan-nkl/RASPI3-DRV8825#4]
Allow input of one number to set the frequency.

For example entering 1000 would change the frequency to 1000 hz and the previously set duty cylce without the need of entering the duty cycle again.

If no duty cycle was ever given, then it should be set to 50%.

**Comment by dan-nkl** [comment]
- [ ] Add this function to the flowchart

**Comment by mauricesifrt** [comment]
Will be added in v1.1.0
